name: openfe_env
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - jupyterlab
  - notebook
  - openfe
  - pip
  - py3dmol
  - pytest
  - pytest-xdist
  - python
  - rdkit>=2025.09.1  # https://github.com/OpenFreeEnergy/gufe/pull/665
