name: "Daily package install tests."
on:
  workflow_dispatch:
  schedule:
    # At 03:00 UTC daily
    - cron: "0 3 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  package-tests:
    runs-on: ubuntu-latest
    name: "main branch long tests"
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"

      - name: "Setup Micromamba"
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: openfe_env
          cache-environment: true
          cache-downloads: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          create-args: >-
            python=3.12
          init-shell: bash

      - name: "install extra deps"
        run: pip install pipx wheel twine readme-renderer

      - name: "build sdist"
        run: pipx run build --sdist --outdir dist

      - name: "check package build"
        run: |
          dist=$(ls -t1 dist/openfe-*tar.gz | head -n1)
          test -n "${dist}" || { echo "no distribution found"; exit 1; }
          twine check $dist

      - name: "install from source dist"
        working-directory: ./dist
        run: python -m pip install openfe-*tar.gz

      - name: "run tests"
        working-directory: ./dist
        env:
          OFE_SLOW_TESTS: "true"
        run: |
          pytest -n auto -v --pyargs openfe.tests
          pytest -n auto -v --pyargs openfecli.tests
